extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:react-hooks/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
  - react-refresh
rules:
  no-shadow: off
  "@typescript-eslint/no-shadow":
    - error
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .tsx
  comma-dangle:
    - error
    - always-multiline
env:
  browser: true
  jest/globals: true
settings:
  react:
    pragma: React
