semi: true
trailingComma: all
singleQuote: true
printWidth: 80
tabWidth: 2
useTabs: false
jsxSingleQuote: true
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder:
  - '^react'
  - '^@/.*$'
  - '^[^.]*$'
  - "^.+\\.(scss|sass|css)$"
  - "^.+\\.(png|jpg|gif|svg)$"
  - "^.+\\.(txt|md|json)$"
importOrderSeparation: true
importOrderSortSpecifiers: true
